[2024-11-04T15:14:05.661+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_dag.load_VBAK_to_bq scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T15:14:05.682+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_dag.load_VBAK_to_bq scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T15:14:05.682+0100] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-11-04T15:14:05.682+0100] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-11-04T15:14:05.683+0100] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-11-04T15:14:05.705+0100] {taskinstance.py:1304} INFO - Executing <Task(GCSToBigQueryOperator): load_VBAK_to_bq> on 2024-11-03 00:00:00+00:00
[2024-11-04T15:14:05.716+0100] {standard_task_runner.py:55} INFO - Started process 9653 to run task
[2024-11-04T15:14:05.723+0100] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bq_dag', 'load_VBAK_to_bq', 'scheduled__2024-11-03T00:00:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/extraction_dag.py', '--cfg-path', '/tmp/tmpgejyhe5u']
[2024-11-04T15:14:05.726+0100] {standard_task_runner.py:83} INFO - Job 115: Subtask load_VBAK_to_bq
[2024-11-04T15:14:05.831+0100] {task_command.py:389} INFO - Running <TaskInstance: gcs_to_bq_dag.load_VBAK_to_bq scheduled__2024-11-03T00:00:00+00:00 [running]> on host 896d6d1d67ca
[2024-11-04T15:14:05.982+0100] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=gcs_to_bq_dag
AIRFLOW_CTX_TASK_ID=load_VBAK_to_bq
AIRFLOW_CTX_EXECUTION_DATE=2024-11-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-11-03T00:00:00+00:00
[2024-11-04T15:14:06.002+0100] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-11-04T15:14:06.027+0100] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-11-04T15:14:06.028+0100] {gcs_to_bigquery.py:367} INFO - Using existing BigQuery table for storing data...
[2024-11-04T15:14:06.053+0100] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-11-04T15:14:06.176+0100] {gcs.py:333} ERROR - Download attempt of object: VBAK.csv from eltl-project-raw-data has failed. Attempt: 1, max 1.
[2024-11-04T15:14:06.176+0100] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 1089, in download_blob_to_file
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 984, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/download.py", line 233, in consume
    retriable_request, self._get_status_code, self._retry_strategy
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/_request_helpers.py", line 148, in wait_and_retry
    response = func()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/download.py", line 214, in retriable_request
    self._process_response(result)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/_download.py", line 189, in _process_response
    response, _ACCEPTABLE_STATUS_CODES, self._get_status_code
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/_helpers.py", line 113, in require_status_code
    *status_codes
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 395, in execute
    self.configuration = self._check_schema_fields(self.configuration)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 538, in _check_schema_fields
    object_name=source_object,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 324, in download
    return blob.download_as_bytes()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1401, in download_as_bytes
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 1092, in download_blob_to_file
    _raise_from_invalid_response(exc)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 4368, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.NotFound: 404 GET https://storage.googleapis.com/download/storage/v1/b/eltl-project-raw-data/o/VBAK.csv?alt=media: No such object: eltl-project-raw-data/VBAK.csv: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
[2024-11-04T15:14:06.193+0100] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_to_bq_dag, task_id=load_VBAK_to_bq, execution_date=20241103T000000, start_date=20241104T141405, end_date=20241104T141406
[2024-11-04T15:14:06.223+0100] {standard_task_runner.py:105} ERROR - Failed to execute job 115 for task load_VBAK_to_bq (404 GET https://storage.googleapis.com/download/storage/v1/b/eltl-project-raw-data/o/VBAK.csv?alt=media: No such object: eltl-project-raw-data/VBAK.csv: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>); 9653)
[2024-11-04T15:14:06.257+0100] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-11-04T15:14:06.305+0100] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
